# XGBoost Assignment - Iris Species

In [1]:
# load library
import pandas as pd

# read data from CSV
df = pd.read_csv('./dataset/iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [2]:
# number of rows and columns
df.shape

(150, 5)

In [3]:
# summary of the data: column names, total no.of non-null values, data types, memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
# summary statistics for all data types
df.describe(include='all')

sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [5]:
# check for missing values
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
# print duplicate values
df[df.duplicated()]

sepal_length  sepal_width  petal_length  petal_width    species
142           5.8          2.7           5.1          1.9  virginica

In [7]:
# drop duplicate values
df = df.drop_duplicates()

In [8]:
# check for duplicate values
df.duplicated().sum()

0

In [9]:
# number of rows and columns
df.shape

(149, 5)

In [10]:
# importing LabelEncoder to convert categorical value to numeric
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['species'] = label_encoder.fit_transform(df['species'])

In [11]:
# count of unique values for 'species' column in the Dataframe
df['species'].value_counts()

species
0    50
1    50
2    49
Name: count, dtype: int64

In [12]:
# spliting the feature and target varibale
X = df.drop('species', axis=1)
y = df['species']

In [13]:
print(X.shape)
print(y.shape)

(149, 4)
(149,)


In [14]:
# 'train_test_split' to split the dataset into Training & Test Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(119, 4)
(30, 4)
(119,)
(30,)


In [16]:
!pip show xgboost

Name: xgboost
Version: 2.0.3
Summary: XGBoost Python Package
Home-page: 
Author: 
Author-email: Hyunsu Cho <chohyu01@cs.washington.edu>, Jiaming Yuan <jm.yuan@outlook.com>
License: Apache-2.0
Location: C:\Users\rahul bhutekar\ds_class\Lib\site-packages
Requires: numpy, scipy
Required-by: 


In [17]:
# importing 'xgboost' and 'XGBClassifier'
import xgboost
from xgboost import XGBClassifier
model = XGBClassifier()

# train the model with training data
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [18]:
# make prediction on test data
y_pred = model.predict(X_test)

In [19]:
# evaluate accuracy on the model
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f'Test accuracy of XGBoost Iris model is: {accuracy*100:.2f}%')

Test accuracy of XGBoost Iris model is: 93.33%


In [20]:
# evaluate accuracy on trained dataset
train_pred = model.predict(X_train)
training_accuracy = accuracy_score(y_train, train_pred)
print(f'Training accuracy of XGBoost Iris model is: {accuracy*100:.2f}%')

Training accuracy of XGBoost Iris model is: 93.33%


In [21]:
# trying different performance metrics
from sklearn.metrics import classification_report, confusion_matrix
classification_report_result = classification_report(y_test, y_pred)
confusion_matrix_result = confusion_matrix(y_test, y_pred)

print('Classification Report: \n', classification_report_result)
print('Confusion Matrix: \n', confusion_matrix_result)

Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.91      0.91      0.91        11
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30

Confusion Matrix: 
 [[ 9  0  0]
 [ 0 10  1]
 [ 0  1  9]]
